/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        try{
            FileReader jsonFiles =new FileReader("recentquotes.json");

            ArrayList<Quotes> quotes=jsonFileReading(jsonFiles);

            int rand =(int)(Math.random() * (quotes.size()));

            System.out.println(quotes.get(rand).toString());


        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
    public static ArrayList<Quotes> jsonFileReading(FileReader jsonFile){
        Gson gson = new Gson();
        BufferedReader reader = new BufferedReader(jsonFile);
        ArrayList<Quotes> quotes =gson.fromJson(reader,new TypeToken<ArrayList<Quotes>>() {}.getType());
        try{
            reader.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return quotes;
    }
}

